### ISSUE TITLE
Initial suggestions for plugin release 

### ISSUE THREAD

**Issue by misraved** [theapsgroup/steampipe-plugin-clickup#1]
Thanks for this amazing plugin @graza-io 😄 . I have been playing around the tables and they were very informative 👍 . The structure looks great. We have a few minor suggestions before we can push the plugin to the hub, please let us know if you have any questions.

1. Could we use the following query in the `README` and the `docs/index.md` files:

  ```
  select
    id,
    name,
    color
  from
    clickup_team;
  ```
  It is essentially the same as `select * from clickup_team` but I guess it would look better to have all the columns listed out. We can also use this query in social graphics(Simple yet powerful).

2. Could we add the `contributing` section at the end of the README file? Please refer to https://github.com/turbot/steampipe-plugin-pagerduty#contributing for more information

3. Could we add the following query in the `docs/index.md` file along with sample output:

```
select
  id,
  name,
  color
from
  clickup_team;
```
Could we also update `# ClickUp + Turbot Steampipe` to `# ClickUp + Steampipe`?

4. Could you please add the `Credentials` section in the `docs/index.md` file, mentioning the permission scope (if required) to query the tables?

5. The `config/clickup.spc` should look something like this:

```
connection "clickup" {
  plugin = "theapsgroup/clickup"

  # ClickUp API token
  # This can also be set via the `CLICKUP_TOKEN` environment variable.
  # token = "pk_xxxxxxx_xxxxxxxxxxxxx"
}
```

6. The formatting in the table docs is slightly different from what we follow across all the documents. Could you please update it as follows:

Existing:

``` 
### Get a folder by ID

```sql
select
    id,
    name,
    order_index,
    hidden,
    space_id,
    task_count,
    archived,
from
    clickup_folder
where
    id = '7fsd72'
```

Updated:

```
### Get a folder by ID

```sql
select
  id,
  name,
  order_index,
  hidden,
  space_id,
  task_count,
  archived,
from
  clickup_folder
where
  id = '7fsd72';
```
The semicolons are also missing at the end of query examples, could you please add them at the end of query examples?

7. The current table examples are great but they still feel a bit light. Could we have 1-2 additional example queries per table?

8. The table descriptions are missing, could we please add them? Currently, the inspect command returns the following result:

```
> .inspect clickup
+-------------------------+-------------+
| table                   | description |
+-------------------------+-------------+
| clickup_folder          |             |
| clickup_folderless_list |             |
| clickup_goal            |             |
| clickup_list            |             |
| clickup_list_member     |             |
| clickup_space           |             |
| clickup_task            |             |
| clickup_task_assignee   |             |
| clickup_task_watcher    |             |
| clickup_team            |             |
| clickup_team_member     |             |
+-------------------------+-------------+
```

9. I did check the SDK for pagination, but couldn't find any. Does the SDK support pagination, backoff, and retry functionality? Please refer to https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information.

Overall the plugin looks great, after the above suggestions are addressed we can push the plugin to the hub 👍 .

Thanks a lot for the plugin @graza-io, eagerly waiting to push it to the hub 👍 .

**Comment by graza-io** [comment]
https://github.com/theapsgroup/steampipe-plugin-clickup/commit/7e0179a315b16909a22bd5b6836f9f064f13ab3a - covers 1,2,3,4,5

https://github.com/theapsgroup/steampipe-plugin-clickup/commit/7dc1d9a13bf84b56229ca89280902e48f2cea2ed - covers 8

https://github.com/theapsgroup/steampipe-plugin-clickup/commit/1aa30af6d588db65eada0bf2c02a9d41a6b55afc - covers 6

**Comment by graza-io** [comment]
9 - pagination is only really in one place https://github.com/theapsgroup/steampipe-plugin-clickup/blob/1aa30af6d588db65eada0bf2c02a9d41a6b55afc/clickup/table_task.go#L36

**Comment by graza-io** [comment]
As for 7, more examples... that's where things become difficult, since all the tables (except teams) require a filter to be applied, you generally want all the records (even if you only want a subset of columns)... will think on it and attempt to get something in place soon.

**Comment by graza-io** [comment]
I'd actually like to get #2 ironed out before we publish to the hub, since it'll be a breaking change to current code.

**Comment by graza-io** [comment]
Some outstanding issues, albeit mostly with the underlying SDK, issue raised see [here](https://github.com/raksul/go-clickup/issues/37)

**Comment by graza-io** [comment]
I believe this is now done, issue on tasks not returning as expected but will raise separately.
